<a href="https://colab.research.google.com/github/IBM-EPBL/IBM-Project-8352-1658915855/blob/main/Asgmt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
planet = "Earth"
diametre = "12742"
print('The Diametre of {} is {} kilometres'.format(planet, diametre))

The Diametre of Earth is 12742 kilometres


In [4]:
d= {'k1' :[1, 2, 3, {'tricky' :['oh', 'man', 'inception', {'target' :[1, 2, 3, 'hello']}]}]}
print( d['k1'][3]["tricky"][3]['target' ][3])

hello


In [5]:
import numpy as np
x = np.arange(0, 9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
import numpy as np
arr= np.arange(20,36,2)
print("Array of all Even Numbers from 20 to 36")
print(arr)

Array of all Even Numbers from 20 to 36
[20 22 24 26 28 30 32 34]


In [7]:
import numpy as np
arr = np.ones(10)*5
print("Array of 10 Fives")
print(arr)

Array of 10 Fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [8]:
import numpy as np
a = np.array([1,2,3])
print(a)
b = np.array([4,5,6])
print(b)
print("Concatination of a and b")
print(np.concatenate((a, b)))

[1 2 3]
[4 5 6]
Concatination of a and b
[1 2 3 4 5 6]


In [9]:
import numpy as np
arr = np.zeros(10)
print("Array of 10 Zeros")
print(arr)

Array of 10 Zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
string = "Hai there Samuel!"
words = string.split(',')
print( wordsm)

['Hai there Samuel!']
